# This workflow will build and sign a new release of your library and publish it to Maven Central.
# It is triggered manually by creating a new release in the GitHub UI.

name: Publish Release to Maven Central

on:
  release:
    types: [ created ] # This workflow runs when a new GitHub release is created

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_TOKEN }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryPassword: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}

    steps:
      # 1. Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Gradle dependencies
      - name: Cache Gradle build
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      # 3. Grant execute permission for gradlew
      - name: Grant Gradlew executable permissions
        run: chmod +x gradlew

      - name: Derive version from tag
        id: version
        run: |
          RAW_TAG='${{ github.ref_name }}'
          VERSION="${RAW_TAG#v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    # 4. Import and fix the GPG key
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET_KEY }}
          passphrase: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}

      # Optional: verify key import
      - name: Verify GPG key
        run: gpg --list-secret-keys

      # 5. Publish, Close, and Release to Maven Central
      - name: Publish Release to Maven Central
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ env.ORG_GRADLE_PROJECT_signingInMemoryKey }}
          ORG_GRADLE_PROJECT_signingInMemoryPassword: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_TOKEN }}
        run: |
          ./gradlew clean \
            -Pversion=${{ steps.version.outputs.version }} \
            publishAllPublicationsToMavenCentral \
            --no-daemon --stacktrace
