# This workflow will build and sign a new release of your library and publish it to Maven Central.
# It is triggered manually by creating a new release in the GitHub UI.

name: Publish Release to Maven Central

on:
  release:
    types: [created] # This workflow runs when a new GitHub release is created

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      MAVEN_CENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY: ${{ secrets.GPG_SECRET_KEY }}
      SIGNING_PASSWORD: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}

    steps:
      # 1. Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          for v in OSSRH_USERNAME OSSRH_TOKEN GPG_SECRET_KEY GPG_SECRET_KEY_PASSPHRASE GPG_SIGNING_KEY_ID; do
            if [ -z "${!v}" ]; then
              echo "Missing secret: $v" >&2
              exit 1
            fi
          done
       

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache Gradle build
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      # 3. Grant execute permission for gradlew
      - name: Grant Gradlew executable permissions
        run: chmod +x gradlew

      - name: Derive version from tag
        id: version
        run: |
          RAW_TAG='${{ github.ref_name }}'
          VERSION="${RAW_TAG#v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      # Optional: verify key import
      - name: Verify GPG key
        run: gpg --list-secret-keys

      # 5. Publish, Close, and Release to Maven Central
      - name: Publish Release to Maven Central
        run: |
          ./gradlew \
            -PmavenCentralUsername="$MAVEN_CENTRAL_USERNAME" \
            -PmavenCentralPassword="$MAVEN_CENTRAL_PASSWORD" \
            -Pversion=${{ steps.version.outputs.version }} \
           :nicetoast:publishToMavenCentral --info --stacktrace
